version: '3'
services:
  web:
    build: .
    ports:
     - "8081:8080"
    env_file:
      - .env.${ENV}
    depends_on:
      - db
    volumes:
      - ./:/src
  db:
    restart: always
    image: postgres
    env_file:
      - .env.${ENV}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
