version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./web:/usr/app
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/count-easy
      PORT: 8080
  db:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
